#  ______ _    _ 
# |  ____| |  | |
# | |__  | |__| | Author:		Foster Hangdaan
# |  __| |  __  | Website:	www.fosterhangdaan.com
# | |    | |  | | Github:		https://github.com/FosterHangdaan
# |_|    |_|  |_|
#
# This configuration file serves as the main entry point for Starship.
#
# You can change default starship.toml file location with STARSHIP_CONFIG
# environment variable: export STARSHIP_CONFIG=/path/to/config
#
# If using FISH, you can export a variable using:
# set -gx STARSHIP_CONFIG /path/to/config

# Don't print a new line at the start of the prompt
add_newline = true

# Prompt Format
format = """
$username$hostname$git_status$git_state
$directory$git_branch$python$character"""

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[character]
success_symbol = "[](bold green)"
error_symbol = "[X](bold red)"
disabled = false

[directory]
truncation_symbol = ".../"
truncate_to_repo = true
style = "bold cyan"
format = "[$path$read_only ]($style)"

[username]
style_user = "bg:#268bd2 fg:white bold"
style_root = "bg:#268bd2 fg:red bold"
format = "[  $user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[@$hostname ](bg:#268bd2 fg:white bold)'
disabled = false

[git_status]
style = "bg:#6c71c4 bold"
format = '([   $all_status$ahead_behind]($style))'
conflicted = "x${count} "
ahead = " x${count} "
behind = " x${count} "
diverged = "x${count} "
untracked = " x${count} "
stashed = "x${count} "
modified = " x${count} "
staged = " x${count} "
renamed = "﬍ x${count} "
deleted = " x${count} "

[git_branch]
style = "fg:purple bold"
symbol = " "
format = 'on [$symbol$branch]($style) '
truncation_length = 10
truncation_symbol = "..."

[git_state]
style = "bg:#6c76c4 bold"
format = '\([$state($progress_current/$progress_total)]($style)\)'

[python]
style = "yellow bold"
symbol = "🐍 "
format = 'via [${symbol}${pyenv_prefix}${version}(\($virtualenv\))]($style) '
python_binary = "python3"
scan_for_pyfiles = true
