#  ______ _    _ 
# |  ____| |  | |
# | |__  | |__| | Author:		Foster Hangdaan
# |  __| |  __  | Website:	www.fosterhangdaan.com
# | |    | |  | | Github:		https://github.com/FosterHangdaan
# |_|    |_|  |_|
#
# This configuration file serves as the main entry point for Starship.
#
# You can change default starship.toml file location with STARSHIP_CONFIG
# environment variable: export STARSHIP_CONFIG=/path/to/config
#
# If using FISH, you can export a variable using:
# set -gx STARSHIP_CONFIG /path/to/config

# Don't print a new line at the start of the prompt
add_newline = true

# Prompt Format
format = """
$username$hostname$git_branch$git_status$git_state$python$rust
$directory$character"""

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[character]
success_symbol = "[](bold green)"
error_symbol = "[X](bold red)"
disabled = false

[directory]
truncation_symbol = ".../"
truncate_to_repo = true
style = "bold cyan"
format = "[$path$read_only ]($style)"

[username]
style_user = "bg:#f4005f fg:#1a1a1a"
style_root = "bg:#f4005f fg:white"
format = "[  $user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[@$hostname ](bg:#f4005f fg:#1a1a1a bold)'
disabled = false

[git_status]
style = "fg:#1a1a1a bg:#9d65ff bold"
format = '([| $all_status$ahead_behind]($style))'
conflicted = "x${count} "
ahead = "x${count} "
behind = "x${count} "
diverged = "x${count} "
untracked = "x${count} "
stashed = "x${count} "
modified = "x${count} "
staged = "x${count} "
renamed = "﬍x${count} "
deleted = "x${count} "

[git_branch]
style = "fg:#1a1a1a bg:#9d65ff bold"
symbol = " "
format = '[ $symbol$branch ]($style)'
truncation_length = 10
truncation_symbol = "..."

[git_state]
style = "fg:#1a1a1a bg:#9d65ff bold"
format = '\([| $state($progress_current/$progress_total)]($style)\)'

[python]
style = "fg:#1a1a1a bg:#e0d561 bold"
symbol = " "
format = '[ ${symbol}${pyenv_prefix}${version}(\($virtualenv\)) ]($style)'
python_binary = "python3"
scan_for_pyfiles = true

[rust]
style = "fg:#1a1a1a bg:#e0d561 bold"
symbol = " "
format = "[ $symbol$version ]($style)"
